export const metadata = {
  title: 'Blog List',
  description: 'Generated by create next app',
}

export default function BlogListLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
    {children}
    </>
  )
}
