'use client'

import Header from '@/components/Header';
import Container from 'react-bootstrap/Container';
import './globals.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import { Inter } from 'next/font/google';
import Footer from '@/components/Footer';
import { ToastContainer} from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/> 
        <Container style={{minHeight: 'calc(100vh - 120px)'}}>
          {children}
        </Container> 
        <ToastContainer />
        <Footer/>        
      </body>
    </html>
  )
}
