export const metadata = {
    title: 'Blog Detail',
    description: 'Generated by create next app',
  }
  
  export default function ViewDetailLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
      <>
      {children}
      </>
    )
  }
  